---
- name: Install and configure frontend server
  hosts: frontend
  become: yes

  tasks:
  - name: set hostname
    ansible.builtin.hostname: name=c8.local  
  - name: disable selinux
    ansible.posix.selinux: state=disabled  
  - name: Get the list of services (to check if firewalld exists because in aws img dont exists)
    service_facts:
  - name: disable firewalld
    service: name=firewalld state=stopped enabled=no
    when: "'firewalld.service' in services" # if no exists, no return an error and stop the playbook
  - name: install nginx
    yum: name=nginx state=latest
  - name: copy proxy config file
    template: src=nginx.conf dest=/etc/nginx/nginx.conf 
  - name: start nginx
    service: name=nginx state=started enabled=yes  


